### ISSUE TITLE
Multiple requests in same file

### ISSUE THREAD

**Issue by ssipos90** [nicwest/vim-http#10]
I'm having some trouble using your plugin having multiple requests. It keeps modifying my files for some reason, it doesn't run the request under cursor, but the first one, then it ads Origin on line 1 and content-length where I have the cursor. 
Sometimes it tries to run the whole buffer as one request.

What am I doing wrong?

```sh
###
GET http://localhost:8000/projects HTTP/1.1
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8000/projects HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "Learn rust3"
}

###

PATCH http://localhost:8000/projects/5 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "Learning rust 5"
}
```

Thanks!

**Comment by nicwest** [comment]
Sorry for the delay! did you sort this out?

If you have multiple requests in the same file you need to use visual select (`v` or `V`) to select the request you want to execute before using `:Http`. otherwise it tries to treat the whole document as a request.

You can also stop the script from adding anything to your request by adding this to your vimrc or similar:

```viml
let g:vim_http_clean_before_do = 0
```

**Comment by nicwest** [comment]
https://asciinema.org/a/rgEl44q8ttqnSVIdBBicny9xZ

**Comment by ssipos90** [comment]
Thanks for the reply and help. As far as I remember, I did try to run with visual line.

Anyway, when I'll get back to the project where I'm using your plugin, I'll get back to you.

I'm gonna close this, thanks again.
